baseurl: ""
url: "https://imyashvinder.github.io/"
# remote_theme: daattali/beautiful-jekyll

plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Site settings (customize!)
title: "Yashvinder Hooda"
description: "Cloud Engineer, Cricket Enthusiast, Traveler"
author: "Yashvinder Hooda"

avatar: "/assets/img/avatar-icon.png"
round-avatar: true

navbar-links:
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: "https://beautifuljekyll.com"
    - Learn markdown: "https://www.markdowntutorial.com/"
  Author's home: "https://deanattali.com"

social-network-links:
  email: "someone@example.com"
  rss: true
  facebook: deanattali
  github: daattali
  twitter: daattali
  patreon: DeanAttali
  youtube: "@daattali"
  whatsapp: 15551212

rss-description: "This website is a virtual proof that I'm awesome"

share-links-active:
  twitter: true
  facebook: true
  linkedin: true
  vk: false
  reddit: false

url-pretty: "MyWebsite.com"
title-on-all-pages: true

excerpt_length: 50
feed_show_excerpt: true
feed_show_tags: true
post_search: true
edit_page_button: true
navbar-var-length: false

page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"

date_format: "%B %-d, %Y"
timezone: "America/Toronto"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      social-share: true
  -
    scope:
      path: ""
    values:
      layout: "page"

exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

